engines:
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
ratings:
  paths:
    - "**.go"
exclude_paths:
  - "utils/graph-builder/js-yaml.min.js"
  - "utils/graph-builder/cytoscape-cxtmenu.js"
