engines:
  gofmt:
    enabled: true
  golint:
    enabled: true
    checks:
      GoLint/Imports/ImportDot:
        enabled: false
  govet:
    enabled: true
ratings:
  paths:
    - "**.go"
exclude_paths:
  - "utils/graph-builder/js-yaml.min.js"
  - "utils/graph-builder/cytoscape-cxtmenu.js"
  - "pkg/client/petsets/"