sudo: required
language: go
services:
    - docker
go:
  - 1.6
  - 1.7
env:
  - WORKING=$HOME/kube1.5 K8S_TAG=v1.5.4 PUBLISH=1
  - WORKING=$HOME/kube1.4 K8S_TAG=v1.4.9
matrix:
  exclude:
    - go: 1.6
      env: WORKING=$HOME/kube1.5 K8S_TAG=v1.5.4 PUBLISH=1
    - go: 1.7
      env: WORKING=$HOME/kube1.4 K8S_TAG=v1.4.9
cache:
  directories:
    - $HOME/kube1.5
    - $HOME/kube1.4
script:
  - go get github.com/Masterminds/glide
  - make test
  - make e2e
after_success:
  - make docker-publish
