apiVersion: appcontroller.k8s1/v1alpha1
kind: Dependency
metadata:
  labels:
    kubeac_task: sample
  name: dependency-1
parent: pod/test-pod
child: pod/test-pod-2
---
apiVersion: appcontroller.k8s1/v1alpha1
kind: Dependency
metadata:
  name: dependency-2
parent: pod/test-pod
child: job/test-job
---
apiVersion: appcontroller.k8s1/v1alpha1
kind: Dependency
metadata:
  name: dependency-3
parent: pod/test-pod-3
child: job/test-job
---
apiVersion: appcontroller.k8s1/v1alpha1
kind: Dependency
metadata:
  name: dependency-4
parent: pod/test-pod-3
child: job/nonexistent-job
---
apiVersion: appcontroller.k8s1/v1alpha1
kind: Dependency
metadata:
  name: dependency-5
parent: pod/existing-test-pod
child: job/test-job
---
apiVersion: appcontroller.k8s1/v1alpha1
kind: Dependency
metadata:
  name: dependency-6
parent: job/existing-test-job
child: job/test-job
