apiVersion: appcontroller.k8s2/v1alpha1
kind: Definition
metadata:
  name: pod-definition-1
pod:
  apiVersion: v1
  kind: Pod
  metadata:
    name: test-pod
    labels:
      label1: label1value
      label2: label2value
  spec:
    containers:
      - name: test-container
        image: gcr.io/google_containers/busybox
        command: [ "/bin/sh", "-c", "env"]
    restartPolicy: Never
---
apiVersion: appcontroller.k8s2/v1alpha1
kind: Definition
metadata:
  name: pod-definition-2
pod:
  apiVersion: v1
  kind: Pod
  metadata:
    name: test-pod-2
    labels:
      label1: label1value
      label2: label2value
  spec:
    containers:
      - name: test-container
        image: gcr.io/google_containers/busybox
        command: [ "/bin/sh", "-c", "env"]
    restartPolicy: Never
---
apiVersion: appcontroller.k8s2/v1alpha1
kind: Definition
metadata:
  name: pod-definition-3
pod:
  apiVersion: v1
  kind: Pod
  metadata:
    name: test-pod-3
    labels:
      kubeac_service: sample
  spec:
    containers:
    - command: ["/bin/sh"]
      args:
      - -c
      - sleep 30; echo ok > /tmp/health; sleep 600
      image: gcr.io/google_containers/busybox
      readinessProbe:
        exec:
          command:
          - /bin/cat
          - /tmp/health
      name: test-container
