apiVersion: appcontroller.k8s2/v1alpha1
kind: Definition
metadata:
  name: service-definition-1
service:
  apiVersion: v1
  kind: Service
  metadata:
    name: test-service
  spec:
    ports:
    - port: 80
      protocol: TCP
    selector:
      kubeac_service: sample
